name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Tzunami Premigration Analyzer User Guide.tex
      - name: Compile LaTeX document
        run: pdflatex -pdf -f -interaction=nonstopmode Tzunami Premigration Analyzer User Guide.tex
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: Tzunami Premigration Analyzer User Guide.pdf
