name: Build LaTeX document
on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Tzunami Premigration Analyzer User Guide.tex
      - name: Compile LaTeX document
        run: pdflatex 'Tzunami Premigration Analyzer User Guide.tex'
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: 'Tzunami Premigration Analyzer User Guide.pdf'
      - name: Deploy PDFs to gh-pages
        run: |
         cd document
         git init
         git add *.pdf
         git config --global --add safe.directory /github/workspace
         git config --local user.email "mahesh.dharhari@gmail.com"
         git config --local user.name "maheshdharhari"
         git commit -m 'PDF Deployed on '"$(date +"%D %T")"
      - name: Force push to branch 'Compiled'
        uses: ad-m/github-push-action@v0.8.0
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: Compiled
         force: true
         directory: ./document
