name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Tzunami Premigration Analyzer User Guide.tex
